### ISSUE TITLE
All rules are not enabled for azurerm provider

### ISSUE THREAD

**Issue by soumyabarman** [terraform-linters/tflint-ruleset-azurerm#104]
Hi,

I have installed and configured 'tflint' in my windows 10 PC. Also performed build and installation of the 'azurerm' provider as mentioned in the documentation. But when I run 'tflint --loglevel debug' it states only 3 rules are enabled. Please find the below steps to reproduce the issue.

1. Install tflint binaries using 'choco install tflint' command
2. Clone tflint azurerm repo locally (https://github.com/terraform-linters/tflint-ruleset-azurerm.git)
3. Run 'go build' to create the 'tflint-ruleset-azurerm.exe' from 'tflint-ruleset-azurerm' folder (Pre-requisite : Go Programming Language needs to be installed)
4. Create the '~/.tflint.d/plugins' directory 
5. Copy the 'tflint-ruleset-azurerm.exe' file to '~/.tflint.d/plugins' directory
6. Create a terraform project folder locally and create '.tflint.hcl' file in the project folder with the below content -
config {
  module = true
  force = true
  disabled_by_default = false
}

rule "azurerm_storage_account_invalid_resource_group_name" {
  enabled = true
}

plugin "azurerm" {
  enabled = true  
}
7. Create a main.tf file with the below content in the same project folder-
terraform {
  required_version = ">= 0.13.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.46.0"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "demo@-tflint-rg"
  location = "West US"
}

resource "azurerm_storage_account" "example" {
  name                     = "demotflintstorageacc"
  resource_group_name      = "${azurerm_resource_group.example.name}"
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "GRS"

  tags = {
    environment = "staging"
  }
}
8. Run 'tflint --format json --loglevel debug'. The output will show only 3 rules are enabled
![image](https://user-images.githubusercontent.com/51684627/111382051-ba468480-8663-11eb-849a-7ce94119df96.png)

**Comment by wata727** [comment]
The number displayed here is the number of rules enabled by default in TFLint core, excluding plugins. The rules of this plugin are enabled.

This log message has been fixed in v0.25.
https://github.com/terraform-linters/tflint/commit/8206ee7b24522b1845fcb24958cf479f6e7078db

**Comment by soumyabarman** [comment]
I don't think 'azurerm' plugin rules are enabled as the resource group name has '@' in it (see the terraform code that creates the azure resource group)and it's not failing.

**Comment by wata727** [comment]
Some resources can detect invalid hard-coded resource group names (like [azurerm_bot_channel_directline_invalid_resource_group_name](https://github.com/terraform-linters/tflint-ruleset-azurerm/blob/5f8d86f79c0436595dcf07fb0b4e27e12ae28326/docs/rules/azurerm_bot_channel_directline_invalid_resource_group_name.md) rule), but there are no rules for `azurerm_resource_group` resource's name.

In addition, TFLint cannot evaluate expressions like `${azurerm_resource_group.example.name}`, so no issues are reported here.

**Comment by soumyabarman** [comment]
I am talking about the name attribute inside the **resource** "_azurerm_resource_group_". The name attribute value is specified as **_name = "demo@-tflint-rg"_** which includes **@** as an invalid character
And there is a rule https://github.com/terraform-linters/tflint-ruleset-azurerm/blob/master/rules/apispec/azurerm_storage_account_invalid_resource_group_name.go that checks the **_resource_group_name_** attribute against a Regex pattern for a Storage Account which doesn't allow **_@_** in the resource group name.
![image](https://user-images.githubusercontent.com/51684627/112537571-15ffc480-8d6c-11eb-8ba2-e821ad6fde91.png)
I think the concern here is only the default core rules are loaded and not the rules specified in **_tflint-ruleset-azurerm_** following the above steps as I mentioned.
