### ISSUE TITLE
Rule azurerm_kubernetes_cluster_node_pool_invalid_vm_size not evaluated for default node pool 

### ISSUE THREAD

**Issue by lrslew** [terraform-linters/tflint-ruleset-azurerm#121]
Hello,

It seems that the rule azurerm_kubernetes_cluster_node_pool_invalid_vm_size is not validating the vm_size of the default node pool which needs to be defined in azurerm_kubernetes_cluster. 

When defining a node pool with resource azurerm_kubernetes_cluster_node_pool everything is working fine. 

Is this expected behavior? If yes, it would be also helpful if the default node pool gets evaluated by the rule azurerm_kubernetes_cluster_node_pool_invalid_vm_size as well. 

Regards

**Comment by wata727** [comment]
> Is this expected behavior?

Yes. This rule focus on the `azurerm_kubernetes_cluster_node_pool` resource. When targeting the `default_node_pool` of `azurerm_kubernetes_cluster`, it's a good idea to create a new rule

**Comment by lrslew** [comment]
Thanks for clarifying this. It would be very helpful if the default node pool gets supported in the future. For my perspective, this can be closed.

**Comment by lrslew** [comment]
Expected behavior of the software. Therefore not an issue.
