### ISSUE TITLE
Required tags rule

### ISSUE THREAD

**Issue by jtaylor100** [terraform-linters/tflint-ruleset-azurerm#133]
A feature request:

Something similar to what was stated in terraform-linters/tflint#150 and implemented in terraform-linters/tflint#617 but for Azure resources.

In the config, you should be able to specify a tags attribute in the config block:

```
config {
    tags = ["foo", "bar"]
}
```

All the Azure resources with tags supported would be checked for tags matching these keys and a lint fail would occur for resources without those tags.

**Comment by wata727** [comment]
@guybartal 

> As a Terraform developer I would like to be noticed when I missed required tags resources
so I won't forget to add those when I add new resources in Terraform module
> adding this rule with help solve this issue: https://github.com/orgs/microsoft/projects/232

I think that such an issue should be solved by an approach like `default_tags` in AWS, but it seems a little difficult for Azure. https://github.com/hashicorp/terraform-provider-azurerm/issues/13776
In the meantime, I don't think it's a bad idea to support such functionality in TFLint. 

If you're interested in implementing such a rule, I would like to support it wherever possible.

**Comment by guybartal** [comment]
already implemented that based on AWS rule :)
I'll soon open a PR, would appreciate if you will review and approve it @wata727.
