### ISSUE TITLE
3 default rules enabled

### ISSUE THREAD

**Issue by dassbernd** [terraform-linters/tflint-ruleset-azurerm#138]
Hi, 

I've installed TFLint Ruleset for terraform-provider-azurerm with TFLint v0.30 and Go v1.17 but any tflint --loglevel command enables 3 default rules. I've followed the steps as in the documentation. 

I've checked [this closed issue](https://github.com/terraform-linters/tflint-ruleset-azurerm/issues/104) already but my version is up to date.

**Comment by wata727** [comment]
What problems are you facing? There is no relationship between this log output and the behavior of tflint-ruleset-azrerm.
