### ISSUE TITLE
No Rules for Nested attributes

### ISSUE THREAD

**Issue by castelinowilliam** [terraform-linters/tflint-ruleset-azurerm#147]
```
resource "azurerm_virtual_machine" "example" {
  name                  = local.vm_name
  location              = azurerm_resource_group.main.location
storage_os_disk {
    name              = "myosdisk1"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }
}
```
In TFlint we can only validate the attributes which are mentioned directly, for e.g name, location etc. But how can we validate the attributes which are nested, for e.g. the attributes which are present inside storage_os_disk block. As there are only 2 parameters resourceType and attributeName in template we cant include the sub-attributes.

**Comment by wata727** [comment]
Hi @castelinowilliam,

Please refer to this example. If you can get `hcl.Block`, you can get any nested attributes from it.
https://github.com/terraform-linters/tflint-ruleset-template/blob/19bd9076445b53d36d022f06dd17ed0b43aa3b57/rules/aws_s3_bucket_example_lifecycle_rule.go
