### ISSUE TITLE
Support New Plugin System

### ISSUE THREAD

**Issue by james1miller93** [terraform-linters/tflint-ruleset-azurerm#157]
With the release of the new gRPC plugin system in the main tflint package, the ruleset needs to be updated to support the latest release of tflint (>= v0.35.0).

If the current release of this ruleset (v0.14.0) is used with tflint v0.35.0 it returns the following error:
```bash
Failed to initialize plugins; Incompatible API version with plugin "azurerm". Plugin version: 9, TFLint versions: [10]
```

Please can you update on whether this work is currently underway and what sor of timescales you're looking at for a release if so.

**Comment by wata727** [comment]
I'm working on this now. I plan to release v0.15.0 within a few days.

**Comment by james1miller93** [comment]
Excellent! Thanks @wata727
