### ISSUE TITLE
azurerm_mysql_server gives error on version number

### ISSUE THREAD

**Issue by stumueller** [terraform-linters/tflint-ruleset-azurerm#171]
Using tflint 0.36.2 and azure rm module 0.16.0

tflint errors saying version 8.0 is not a valid value, looking at the ruleset it is expecting 8.0.21

when I change this in the terraform, tflint passes but the deployment fails with a terraform error saying it expects 5.7 or 8.0

**Comment by PatMyron** [comment]
https://github.com/terraform-linters/tflint-ruleset-azurerm/blob/5ee511a69ae38ff92dbef591c1e0b78a2d1d5015/rules/apispec/azurerm_mysql_server_invalid_version.go#L29

related: https://github.com/terraform-linters/tflint-ruleset-azurerm/pull/144, https://github.com/terraform-linters/tflint-ruleset-azurerm/issues/30, https://github.com/terraform-linters/tflint-ruleset-azurerm/issues/64

**Comment by wata727** [comment]
Hmm, This may be a bug.
