### ISSUE TITLE
Add rule for resource missing tags

### ISSUE THREAD

**Issue by guybartal** [terraform-linters/tflint-ruleset-azurerm#193]
As a Terraform developer I would like to be noticed when I missed required tags resources
so I won't forget to add those when I add new resources in Terraform module

**Comment by guybartal** [comment]
adding this rule with help solve this issue: [https://github.com/orgs/microsoft/projects/232](https://github.com/orgs/microsoft/projects/232)

**Comment by wata727** [comment]
Duplicate of https://github.com/terraform-linters/tflint-ruleset-azurerm/issues/133
