### ISSUE TITLE
The rule for IP Address type on Container Instances does not accept None

### ISSUE THREAD

**Issue by arcjor** [terraform-linters/tflint-ruleset-azurerm#233]
The ruleset for IP Address type on container instances does not allow none.
https://github.com/terraform-linters/tflint-ruleset-azurerm/blob/v0.20.0/docs/rules/azurerm_container_group_invalid_ip_address_type.md 

The official documentation indicates this option is supported.
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/container_group#ip_address_type

**Comment by wata727** [comment]
Thank you for reporting this. This seems to be an extended attribute on the provider.
https://github.com/hashicorp/terraform-provider-azurerm/blob/v3.43.0/internal/services/containers/container_group_resource.go#L71
