### ISSUE TITLE
Rule `azurerm_postgresql_server_invalid_version` - Incorrect postgres resource type?

### ISSUE THREAD

**Issue by lonegunmanb** [terraform-linters/tflint-ruleset-azurerm#249]
In this [plugin](https://github.com/terraform-linters/tflint-ruleset-azurerm/blob/737770acf1a52ca293a72bd36e4c737d2af86977/rules/apispec/azurerm_postgresql_server_invalid_version.go#L23-L34) we've restricted the server's version to:

```go
enum: []string{
			"14",
			"13",
			"12",
			"11",
		},
```

In the [document](https://github.com/terraform-linters/tflint-ruleset-azurerm/blob/master/docs/rules/azurerm_postgresql_server_invalid_version.md?plain=1#L46) we described:

>This rule is automatically generated from [azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs). If you are uncertain about the warning, check the following API schema referenced by this rule.

>https://github.com/Azure/azure-rest-api-specs/tree/master/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/stable/2022-12-01/FlexibleServers.json

But the API referenced is about Postgres Flexible Server, which has corresponding resource: [`azurerm_postgresql_flexible_server`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server).

`azurerm_postgresql_server`'s version restriction in API spec is [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/stable/2017-12-01/postgresql.json#L1643-L1658), it should be:

```json
"enum": [
        "9.5",
        "9.6",
        "10",
        "10.0",
        "10.2",
        "11"
      ],
```

We can verify the API version that AzureRM provider is using now [here](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/postgres/client/client.go#L9).

This resource should check `azurerm_postgresql_flexible_server` instead.

**Comment by wata727** [comment]
Fixed by https://github.com/terraform-linters/tflint-ruleset-azurerm/pull/252
