### ISSUE TITLE
Panic caused by azure api spec moved MySQL spec's path

### ISSUE THREAD

**Issue by lonegunmanb** [terraform-linters/tflint-ruleset-azurerm#253]
When I tried to generate rules from azure api specs I met the following error:

>panic: open apispec-rule-gen/azure-rest-api-specs/specification/mysql/resource-manager/Microsoft.DBforMySQL/stable/2021-05-01/mysql.json: no such file or directory

I saw the same error in this repo's pipeline, it seems azure api spec repo has moved MySQL's specs from `specification/mysql/resource-manager/Microsoft.DBforMySQL/stable/xxx` to specification/mysql/resource-manager/Microsoft.DBforMySQL/legacy/stable/`, @wata727 I'd like to submit a pr to update the submodule to the latest version, and fix broken paths in the mappings, could I do that? Thanks.

**Comment by wata727** [comment]
@lonegunmanb Sure! I would be very happy if you could do this.

**Comment by wata727** [comment]
Fixed by https://github.com/terraform-linters/tflint-ruleset-azurerm/pull/257
