### ISSUE TITLE
Missing new B VM Size

### ISSUE THREAD

**Issue by Poil** [terraform-linters/tflint-ruleset-azurerm#342]
Hi

It looks like we are missing new VM type :

https://learn.microsoft.com/en-us/azure/virtual-machines/bsv2-series
https://learn.microsoft.com/en-us/azure/virtual-machines/basv2
https://learn.microsoft.com/en-us/azure/virtual-machines/bpsv2-arm

Regards

**Comment by JannoTjarks** [comment]
Hi @Poil, i think, i added the sizes on my PR from last year: [Adds missing vm sizes of Westeurope and East US #297](https://github.com/terraform-linters/tflint-ruleset-azurerm/pull/297)

Are you using the newest release of the azurerm plugin? [v0.26.0](https://github.com/terraform-linters/tflint-ruleset-azurerm/releases/tag/v0.26.0)

**Comment by JannoTjarks** [comment]
Or is there any specific size, you are missing. Then i can check this up :)

**Comment by JannoTjarks** [comment]
Hi @Poil any update from your side?

**Comment by JannoTjarks** [comment]
@Poil i will close this issue. Please ping us, if the error occurs also in the latest version. From my point of view, this should be fixed.

Thanks!
