### ISSUE TITLE
enhancement: add azurerm provider linting

### ISSUE THREAD

**Issue by wardcomm** [terraform-linters/tflint-ruleset-azurerm#4]
enhancement: add azurerm provider linting

**Comment by wata727** [comment]
@ashemedai Are you still interested in this? I have created a ruleset plugin repository for linting azure resources.

**Comment by ashemedai** [comment]
@wata727 Watanabe-san, I was, but since my last post I resigned from the position where I was using Azure on a daily basis. So I would not be a good person at the moment to help out on that. My apologies.

**Comment by wata727** [comment]
Hi all!

Today, I released tflint-ruleset-azurerm v0.1.0! By this plugin, TFLint can automate more than 200 inspections on Azure resources.

And this is the first plugin released by this organization. Various problems may occur. Please give us your feedback.

Finally, thank you, @ashemedai. The repositories you gave me helped automate the generation of many rules. Thank you again.
